<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:portlet="http://www.ibm.com/wps/c2a" xmlns:tns="http://typik.bitik.project.TYPIK.BITIK.PROJECT.Types.Menu/" xmlns:tns0="http://typik.bitik.project" name="TYPIK_BITIK_PROJECT_Types_Menu_Service" targetNamespace="http://typik.bitik.project.TYPIK.BITIK.PROJECT.Types.Menu/">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://typik.bitik.project">
      <xsd:simpleType name="MyDatatype">
        <xsd:restriction base="xsd:string"/>
      </xsd:simpleType>
    </xsd:schema>
  </types>
  <message name="SourceAction_Response">
    <part name="MyDatatype_Output" type="tns0:MyDatatype"/>
  </message>
  <portType name="TYPIK_BITIK_PROJECT_Types_Menu_Service">
    <operation name="TYPIK_BITIK_PROJECT_Types_Menu">
      <output message="tns:SourceAction_Response"/>
    </operation>
  </portType>
  <binding name="TYPIK_BITIK_PROJECT_Types_Menu_Binding" type="tns:TYPIK_BITIK_PROJECT_Types_Menu_Service">
    <portlet:binding/>
    <operation name="TYPIK_BITIK_PROJECT_Types_Menu">
      <portlet:action actionNameParameter="ACTION_NAME_PARAM" caption="Action.Caption" name="SourceAction" type="standard"/>
      <output>
        <portlet:param boundTo="request-attribute" caption="Property.Caption" name="outputProperty" partname="MyDatatype_Output"/>
      </output>
    </operation>
  </binding>
</definitions>
